CFLAGS = -std=gnu11 -Wall -Wextra -lm

.PHONY: all
all: serial parallel parallel_v2

.PHONY: clean
clean:
	$(RM) serial parallel parallel_v2

serial: serial.c

parallel: parallel.c

parallel_v2: parallel_v2.c
