CFLAGS = -std=gnu11 -Wall -Wextra -lm

.PHONY: all
all: hadamard hadamard_v1 hadamard_v2

.PHONY: clean
clean:
	$(RM) hadamard

hadamard: hadamard.c

hadamard_v1: hadamard_v1.c

hadamard_v2: hadamard_v2.c
